### ISSUE TITLE
Error compiling on Fedora 33

### ISSUE THREAD

**Issue by lucat** [AudioSceneDescriptionFormat/asdf-rust#12]
Being new to rust I do not know if it is a problem with asdf-rust or more probably with something missing in my rust build chain.

Maybe someone could give me an hint how to solve this.

Trying to compile I got this at the end:

[...]
  Compiling libflac-sys v0.2.0
       Fresh libsamplerate-sys v0.1.10
       Fresh rand v0.7.3
       Fresh simba v0.1.5
       Fresh thiserror v1.0.23
       Fresh vorbisfile-sys v0.0.8
     Running `rustc --crate-name libflac_sys --edition=2018 /home/lt/.cargo/registry/src/github.com-1ecc6299db9ec823/libflac-sys-0.2.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="build-flac"' --cfg 'feature="build-ogg"' --cfg 'feature="cmake"' --cfg 'feature="default"' -C metadata=246f47f88bf57a8d -C extra-filename=-246f47f88bf57a8d --out-dir /home/lt/asdf-rust/target/release/deps -L dependency=/home/lt/asdf-rust/target/release/deps --extern libc=/home/lt/asdf-rust/target/release/deps/liblibc-e1285449eae9a394.rmeta --cap-lints allow -L native=/home/lt/asdf-rust/target/release/build/libflac-sys-419339b09ba7b38c/out/lib -L native=/home/lt/asdf-rust/target/release/build/libflac-sys-419339b09ba7b38c/out/build/src/libFLAC -l static=ogg -l static=FLAC`
       Fresh rand_distr v0.2.2
       Fresh nalgebra v0.21.1
       Fresh asdfspline v0.0.0 (/home/lt/asdf-rust/asdfspline)
error: could not find native static library `ogg`, perhaps an -L flag is missing?

error: aborting due to previous error

Error: CliError { error: Some(could not compile `libflac-sys`

Caused by:
    process didn't exit successfully: `rustc --crate-name libflac_sys --edition=2018 /home/lt/.cargo/registry/src/github.com-1ecc6299db9ec823/libflac-sys-0.2.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="build-flac"' --cfg 'feature="build-ogg"' --cfg 'feature="cmake"' --cfg 'feature="default"' -C metadata=246f47f88bf57a8d -C extra-filename=-246f47f88bf57a8d --out-dir /home/lt/asdf-rust/target/release/deps -L dependency=/home/lt/asdf-rust/target/release/deps --extern libc=/home/lt/asdf-rust/target/release/deps/liblibc-e1285449eae9a394.rmeta --cap-lints allow -L native=/home/lt/asdf-rust/target/release/build/libflac-sys-419339b09ba7b38c/out/lib -L native=/home/lt/asdf-rust/target/release/build/libflac-sys-419339b09ba7b38c/out/build/src/libFLAC -l static=ogg -l static=FLAC` (exit code: 1)), exit_code: 101 }

**Comment by mgeier** [comment]
Thanks for the report!

The error seems to be caused by https://github.com/mgeier/libflac-sys (which is also maintained by me).

I don't know what's the problem, but could you please try to get the latest version of https://github.com/mgeier/libflac-sys via `git` and try compiling it locally with `cargo build`?

Maybe then the error message is a bit more helpful?

Alternatively, you could also try to disable the default features and use the `libFLAC` that's installed on your system.

**Comment by lucat** [comment]
Thank you for the prompt answer!

I tried to clone the   https://github.com/mgeier/libflac-sys repository just now but building it, I got more or less the same error (or at least I don't see any different information of relevance). See below.
The problem seems to be in relation to the submodule ogg in the repository, as the relevant error appears to be
"could not find native static library `ogg`, perhaps an -L flag is missing?"
But if I cd into the submodule and compile with cmake there is no problem at all and I get a static library libogg.a.
Having no knowledge of rustc and cargo infrastructure I have no Idea where this library is expected to be found and if something is wrong in the linking phase.

Isn't libogg linked twice, as libflac also links it?

I will let you know if I have any success with the alternative you proposed.

Here the error building libflac-sys from the repository.

lt@localhost libflac-sys]$ cargo build --verbose
       Fresh cc v1.0.66
       Fresh cmake v0.1.45
       Fresh libc v0.2.85
   Compiling libflac-sys v0.2.0 (/home/lt/libflac-sys)
     Running `rustc --crate-name libflac_sys --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="build-flac"' --cfg 'feature="build-ogg"' --cfg 'feature="cmake"' --cfg 'feature="default"' -C metadata=e297a77ecca67196 -C extra-filename=-e297a77ecca67196 --out-dir /home/lt/libflac-sys/target/debug/deps -C incremental=/home/lt/libflac-sys/target/debug/incremental -L dependency=/home/lt/libflac-sys/target/debug/deps --extern libc=/home/lt/libflac-sys/target/debug/deps/liblibc-08f0d9f107175437.rmeta -L native=/home/lt/libflac-sys/target/debug/build/libflac-sys-64111617e2003a9b/out/lib -L native=/home/lt/libflac-sys/target/debug/build/libflac-sys-64111617e2003a9b/out/build/src/libFLAC -l static=ogg -l static=FLAC`
error: could not find native static library `ogg`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `libflac-sys`

Caused by:
  process didn't exit successfully: `rustc --crate-name libflac_sys --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="build-flac"' --cfg 'feature="build-ogg"' --cfg 'feature="cmake"' --cfg 'feature="default"' -C metadata=e297a77ecca67196 -C extra-filename=-e297a77ecca67196 --out-dir /home/lt/libflac-sys/target/debug/deps -C incremental=/home/lt/libflac-sys/target/debug/incremental -L dependency=/home/lt/libflac-sys/target/debug/deps --extern libc=/home/lt/libflac-sys/target/debug/deps/liblibc-08f0d9f107175437.rmeta -L native=/home/lt/libflac-sys/target/debug/build/libflac-sys-64111617e2003a9b/out/lib -L native=/home/lt/libflac-sys/target/debug/build/libflac-sys-64111617e2003a9b/out/build/src/libFLAC -l static=ogg -l static=FLAC` (exit code: 1)
[lt@localhost libflac-sys]$

**Comment by mgeier** [comment]
Thanks for the update!

Maybe the generated OGG library is stored in a different location on your system?

Can you please look into the directory `/home/lt/libflac-sys/target/debug/build/libflac-sys-64111617e2003a9b/out/lib` and check if you find the OGG library (probably a file named `libogg.a` or similar)?
I guess it's not there, but maybe it's in a sub-directory or a parent directory or somewhere around there?

If it is, we can add another `-L` path like it has been done for `libFLAC` on Windows: https://github.com/mgeier/libflac-sys/blob/8ade8e338da644b9f8610db3dbc69ec41f148775/build.rs#L32-L46

> Isn't libogg linked twice in asdf-rust, as libflac also links it?

Yeah, I guess both `libFLAC` and `libvorbis` link to OGG.
Is this a problem for you?
Do you know a way to avoid this?

**Comment by lucat** [comment]
Yes, exactly: on my system the static library is not written in that directory, instead in another with the same name plus "lib64" at the end (I am on a 64 bit system). This is the only difference. So if I add that "64" after "lib" in  line 22 of  build.rs  (libflac-sys repository local copy of yours) and also compile asdf-rust from the local edited copy of the repository - changing line 22 of Cargo.toml (asdf-rust local copy) into 

libflac-sys = { path = "../libflac-sys" }

to use the local copy, then I can compile asdf-rust and install on my system.

I don't think it is a problem to have the double linking to ogg, I was just wondering myself what would happen if you do not build libogg in the libflac-sys.  I lookt at build.rs there and there is a WIHIT_OGG variable, so I guess the features of the flac library would change, not allowing flac in ogg containers. 

I have no idea how this rust / cargo stuff works.  What I write is not meant to be taken as a fix, just a report of what I did to compile. I hope you or someone else can find a solution applicable to all or most linux distributions.

**Comment by mgeier** [comment]
Thanks for the update!

> I have no idea how this rust / cargo stuff works.

I'm not a Rust/Cargo expert either.

But the problem here is that I know even less about CMake. AFAICT, the library directory is somehow chosen by CMake in a platform-specific way.
I don't know if there is a way to force CMake to use a given directory, but this would make the usage in `build.rs` easier.

Anyway, I've just created https://github.com/mgeier/libflac-sys/pull/15, which simply adds the `lib64` directory on top of `lib`.

It should be possible to add arbitrary linker paths, even if some of them don't exist.
The only problem is if multiple of them exist and they contain different variations of the same library, but I hope this doesn't happen in practice.
